### ISSUE TITLE
Spreadsheet not found

### ISSUE THREAD

**Issue by ProgrammerMatt** [burnash/gspread#366]
Hey, I made no changes since last night when it was working. I woke up this morning trying to run the same, unchanged script, and it can't find the spreadsheet. I tried all three methods. Any ideas? I shared with the client email.

**Comment by donkawechico** [comment]
I'm also getting this error. 

However, I haven't seen it work at all yet since I only started trying out this plugin an hour ago. Could be that I've screwed something else up.

Authorization works fine, but even a call to openall() returns an empty list.

**Comment by ProgrammerMatt** [comment]
Does "spreadsheets.google.com/feeds" always report back with "Sorry, unable to open the file at this time." when accessing from browser? (not from client email?) or is that just currently down?

**Comment by donkawechico** [comment]
Correct. When I go to that URL in a browser, I get the error you posted. However, I've never personally tried going to that URL so I have no idea if that has ever resulted in going to something visible from a browser window.

I tried changing my "scope" var to "docs.google.com/spreadsheets" but that (unsurprisingly) threw a scoping error. I really have no idea what that URL is used for or how to find an alternative.

**Comment by virtadpt** [comment]
@ProgrammerMatt @donkawechico I'm getting the same problem, and going to the /feeds URL does always reply with the "Sorry, unable to open the file at this time." error.

**Comment by donkawechico** [comment]
No idea if this is a valid reference for this mysterious "scope" url for sheets, but this could be relevant:

https://developers.google.com/identity/protocols/googlescopes#managerv1beta2

There's nothing specific to sheets, but the Drive API scope URLs are all of the form:
https://www.googleapis.com/auth/drive.stuff.otherstuff

I tried doing the first one, and I got a *different* error from gspread, which feels like progress somehow:
https://www.googleapis.com/auth/drive 

Still nothing resembling success though.

**Comment by donkawechico** [comment]
These are the scope urls for Google Drive, according to the Google APIs Metadata API:
https://www.googleapis.com/discovery/v1/apis/drive/v3/rest?fields=auth(oauth2(scopes))

However, each of those scope urls gives me an error (in html) about the auth token being wrong.

I tried poking around the APIs Explorer to see what I could find. There's this page, which has a button for enabling OAuth2 for Drive API (currently set to OFF for me):
https://developers.google.com/apis-explorer/#search/drive/drive/v3/

I tried turning the button ON and using the scope urls above, and still nothin'

**Comment by michie1** [comment]
Maybe I have a similar problem. I want to delete a worksheet, but I receive the exception "WorksheetNotFound". When I add spreadsheet.worksheets() in the line above the deletion it works fine.

**Comment by virtadpt** [comment]
@ProgrammerMatt It did not.

**Comment by ProgrammerMatt** [comment]
And now it's randomly working... I haven't touched my code since then.

**Comment by zamberjo** [comment]
I'm getting the same error message

>     wks = gc.open("foo")
>       File "/usr/local/lib/python2.7/site-packages/gspread/client.py", line 152, in open
>         raise SpreadsheetNotFound
>     gspread.exceptions.SpreadsheetNotFound

**Comment by zamberjo** [comment]
My fault with #226 I solved the problem

**Comment by donkawechico** [comment]
@zamberjo, that did the trick! I didn't see the "share spreadsheet with the service account email address Google gave you" step.

That solved my issue.

**Comment by puneetkaura** [comment]
@zamberjo  Same here, sharing the sheet with the serviceaccount email id did the trick

**Comment by john1jan** [comment]
Sharing trick worked..awesome..
i shared my sheet with **"client_email"** which i got from .json file , while creating credentials in google console

**Comment by LiberiFatali** [comment]
Fixed this by going to the sheet and share it with generated service account email.

**Comment by keshavneupane** [comment]
even with sharing the generated service account email it did not solve the problem. The script has been running fine till the date (for the last one year) and have not made any changes. It works once and stops working the next time, started seeing this issue from today. the error I get is 
`raise SpreadsheetNotFound
gspread.exceptions.SpreadsheetNotFound` 
Any suggestions would be helpful

**Comment by keshavneupane** [comment]
To solve the issue, I ended up retrying for few times using package "retrying 1.3.3" , most of the time 2 or 3 try was good enough.

**Comment by schwallie** [comment]
I have this issue. I have to unshare and then reshare the sheets. Really time consuming and annoying when ~100 are popping up daily

**Comment by burnash** [comment]
It looks like the issue [has been resolved](https://github.com/burnash/gspread/issues/366#issuecomment-195649799).
