### ISSUE TITLE
Failing Travis CI tests

### ISSUE THREAD

**Issue by artemrys** [burnash/gspread#737]
**Describe the bug**
Tests in Travis CI are failing now.

**To Reproduce**
1. Create PR and make Travis CI run automatic tests.

**Expected behavior**
Passing tests.

**Code example***
PR: https://github.com/burnash/gspread/pull/733
Travis CI run: https://travis-ci.org/github/burnash/gspread/jobs/665077893

**Stack trace or other output that would be helpful**
Several examples:
```
======================================================================

ERROR: test_copy (tests.test.ClientTest)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/burnash/gspread/tests/test.py", line 206, in test_copy

    original_spreadsheet = self.gc.create("Original")

  File "/home/travis/build/burnash/gspread/gspread/client.py", line 217, in create

    json=payload

  File "/home/travis/build/burnash/gspread/gspread/client.py", line 79, in request

    raise APIError(response)

nose.proxy.APIError: {'errors': [{'domain': 'global', 'location': 'Authorization', 'message': 'Invalid Credentials', 'locationType': 'header', 'reason': 'authError'}], 'code': 401, 'message': 'Invalid Credentials'}

-------------------- >> begin captured logging << --------------------

urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): www.googleapis.com:443

urllib3.connectionpool: DEBUG: https://www.googleapis.com:443 "POST /drive/v2/files HTTP/1.1" 401 None
```

```
======================================================================

ERROR: test_add_del_worksheet (tests.test.SpreadsheetTest)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/burnash/gspread/tests/test.py", line 313, in test_add_del_worksheet

    worksheet1 = self.spreadsheet.add_worksheet(worksheet1_name, 1, 1)

  File "/home/travis/build/burnash/gspread/gspread/models.py", line 340, in add_worksheet

    properties = data['replies'][0]['addSheet']['properties']

KeyError: 'addSheet'
```

**Comment by burnash** [comment]
I believe I fixed it in de62b00f0714f13345cde30d88f33225478f1b02
Could you please rebase and recheck?

**Comment by artemrys** [comment]
I've updated my branch in https://github.com/burnash/gspread/pull/733. But looks like that Travis build was not triggered.

**Comment by jayvdb** [comment]
I am still seeing tests failing @burnash , locally and on openSUSE build workers.

```pt
> tox -e py38
GLOB sdist-make: /home/jayvdb/projects/python/gspread/setup.py
py38 create: /home/jayvdb/.cache/tox/gspread/py38
py38 installdeps: -rtest-requirements.txt
py38 inst: /home/jayvdb/.cache/tox/gspread/.tmp/package/1/gspread-3.6.0.zip
py38 testmon: setting TESTMON_DATAFILE=/home/jayvdb/.cache/tox/gspread/py38/.testmondata
py38 installed: betamax==0.8.1,-e git+https://github.com/burnash/betamax-json-body-serializer.git@0945268b69272cf90c55fdfd962f1801295ff30b#egg=betamax_json_body_serializer,cachetools==4.1.1,certifi==2020.6.20,chardet==3.0.4,google-auth==1.22.1,google-auth-oauthlib==0.4.1,gspread==3.6.0,idna==2.10,nose==1.3.7,oauthlib==3.1.0,pyasn1==0.4.8,pyasn1-modules==0.2.8,requests==2.24.0,requests-oauthlib==1.3.0,rsa==4.6,six==1.15.0,urllib3==1.25.10
py38 run-test-pre: PYTHONHASHSEED='603527915'
py38 run-test: commands[0] | nosetests -vv tests/test.py
nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
test_a1_value (tests.test.CellTest) ... ok
test_merge_cells (tests.test.CellTest) ... ERROR
test_numeric_value (tests.test.CellTest) ... ERROR
test_properties (tests.test.CellTest) ... ERROR
test_access_non_existing_spreadsheet (tests.test.ClientTest) ... ok
test_copy (tests.test.ClientTest) ... ok
test_create (tests.test.ClientTest) ... ok
test_import_csv (tests.test.ClientTest) ... ok
test_no_found_exeption (tests.test.ClientTest) ... ok
test_openall (tests.test.ClientTest) ... ok
test_add_del_worksheet (tests.test.SpreadsheetTest) ... ERROR
test_get_worksheet (tests.test.SpreadsheetTest) ... ok
test_properties (tests.test.SpreadsheetTest) ... ok
test_sheet1 (tests.test.SpreadsheetTest) ... ok
test_values_batch_get (tests.test.SpreadsheetTest) ... ERROR
test_values_get (tests.test.SpreadsheetTest) ... ERROR
test_worksheet (tests.test.SpreadsheetTest) ... ok
test_worksheet_iteration (tests.test.SpreadsheetTest) ... ERROR
test_a1_to_rowcol (tests.test.UtilsTest) ... ok
test_addr_converters (tests.test.UtilsTest) ... ok
test_extract_id_from_url (tests.test.UtilsTest) ... ok
test_get_gid (tests.test.UtilsTest) ... ok
test_no_extract_id_from_url (tests.test.UtilsTest) ... ok
test_numericise (tests.test.UtilsTest) ... ok
test_rowcol_to_a1 (tests.test.UtilsTest) ... ok
test_acell (tests.test.WorksheetTest) ... ERROR
test_append_row (tests.test.WorksheetTest) ... ERROR
test_append_row_with_empty_value (tests.test.WorksheetTest) ... ERROR
test_append_row_with_empty_value_and_table_range (tests.test.WorksheetTest) ... ERROR
test_basic_filters (tests.test.WorksheetTest) ... ERROR
test_batch_get (tests.test.WorksheetTest) ... ERROR
test_batch_update (tests.test.WorksheetTest) ... ERROR
test_cell (tests.test.WorksheetTest) ... ERROR
test_clear (tests.test.WorksheetTest) ... ERROR
test_delete_row (tests.test.WorksheetTest) ... ERROR
test_find (tests.test.WorksheetTest) ... ERROR
test_findall (tests.test.WorksheetTest) ... ERROR
test_format (tests.test.WorksheetTest) ... ERROR
test_freeze (tests.test.WorksheetTest) ... ERROR
test_get_all_records (tests.test.WorksheetTest) ... ERROR
test_get_all_records_different_header (tests.test.WorksheetTest) ... ERROR
test_get_all_records_numericise_unformatted (tests.test.WorksheetTest) ... ERROR
test_get_all_records_value_render_options (tests.test.WorksheetTest) ... ERROR
test_get_all_values (tests.test.WorksheetTest) ... ERROR
test_get_all_values_title_is_a1_notation (tests.test.WorksheetTest) ... ERROR
test_insert_row (tests.test.WorksheetTest) ... ERROR
test_range (tests.test.WorksheetTest) ... ERROR
test_reorder_worksheets (tests.test.WorksheetTest) ... ERROR
test_resize (tests.test.WorksheetTest) ... ERROR
test_sort (tests.test.WorksheetTest) ... ERROR
test_update_acell (tests.test.WorksheetTest) ... ERROR
test_update_and_get (tests.test.WorksheetTest) ... ERROR
test_update_cell (tests.test.WorksheetTest) ... ERROR
test_update_cell_multiline (tests.test.WorksheetTest) ... ERROR
test_update_cell_objects (tests.test.WorksheetTest) ... ERROR
test_update_cell_unicode (tests.test.WorksheetTest) ... ERROR
test_update_cells (tests.test.WorksheetTest) ... ERROR
test_update_cells_noncontiguous (tests.test.WorksheetTest) ... ERROR
test_update_cells_unicode (tests.test.WorksheetTest) ... ERROR
test_worksheet_update_index (tests.test.WorksheetTest) ... ERROR

======================================================================
ERROR: test_merge_cells (tests.test.CellTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jayvdb/projects/python/gspread/tests/test.py", line 1179, in test_merge_cells
    self.sheet.update('A1:B2', [[42, 43], [43, 44]])
  File "/home/jayvdb/projects/python/gspread/gspread/utils.py", line 592, in wrapper
    return f(*args, **kwargs)
  File "/home/jayvdb/projects/python/gspread/gspread/models.py", line 1123, in update
    response = self.spreadsheet.values_update(
  File "/home/jayvdb/projects/python/gspread/gspread/models.py", line 236, in values_update
    r = self.client.request('put', url, params=params, json=body)
  File "/home/jayvdb/projects/python/gspread/tests/test.py", line 86, in request
    return super().request(*args, **kwargs)
  File "/home/jayvdb/projects/python/gspread/gspread/client.py", line 64, in request
    response = getattr(self.session, method)(
  File "/home/jayvdb/.cache/tox/gspread/py38/lib/python3.8/site-packages/requests/sessions.py", line 590, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/home/jayvdb/.cache/tox/gspread/py38/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jayvdb/.cache/tox/gspread/py38/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/jayvdb/.cache/tox/gspread/py38/lib/python3.8/site-packages/betamax/adapter.py", line 131, in send
    raise BetamaxError(unhandled_request_message(request,
betamax.exceptions.BetamaxError: A request was made that could not be handled.

A request was made to https://sheets.googleapis.com/v4/spreadsheets/1ZcOTRFxW0XQkXFBt4XectBYteEeFUd4IHFv-re6fwGM/values/%27Sheet1%27%21A1%3AB2?valueInputOption=RAW that could not be found in CellTest.test_merge_cells.

The settings on the cassette are:

    - record_mode: once
    - match_options {'method', 'uri'}.
```

**Comment by lavigne958** [comment]
Hi, I had similar issues recently, some tests were failing for some unknown reason.

I noticed the 'record_mode' that says 'once'.
I tried to run the test with the following environment variable set 'GS_RECORD_MODE=all' and runs fine.

I suppose we look into betamax.

**Comment by jayvdb** [comment]
`GS_RECORD_MODE=all` creates new fixtures which need to be saved for future use.
https://betamax.readthedocs.io/en/latest/record_modes.html

**Comment by lavigne958** [comment]
I opened a new ticket about that 'should we update the cassettes' #821

**Comment by lavigne958** [comment]
travis CI has been disabled, very soon will use github Actions.

Switching from (for now) no CI to github Actions will trigger update of cassettes (I will update them on the way).

Closing this issue.
